 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: maha-maha-deployment
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: maha
   template:
     metadata:
       labels:
         app: maha
     spec:
       containers:
       - name: flasknode
         image: icr.io/maha_expense_tracker2/flask-template2
         imagePullPolicy: Always
         ports:
         - containerPort: 5000
